spring:
  application:
    name: rpm
  datasource:
    url: jdbc:mysql://localhost:3306/pricing?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
nacos:
  host: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos

dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}/
    #address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
    parameters:
      namespace: dc3aec53-2891-4225-be26-0503cf148ab8
server:
  port: 8091
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload